server:
  port: 8100

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: hr
    password: ${password:08031999}
  mail:
    host: smtp.gmail.com
    username: peddojupranavi@gmail.com
    password: 08031999
    port: 587
    properties:
        mail:
           smtp:
              auth: true
              starttls :
                  required : true
                  enable: true
                  
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle10gDialect
    
logging:
  file:
    name: ApplicationBackend-log.txt
